// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://smcqclzehuahihiobhqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNtY3FjbHplaHVhaGloaW9iaHF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4Nzc2MTIsImV4cCI6MjA2NTQ1MzYxMn0.BfAVkz3EqmikSHLhHBfEPgTVzQxFAa-IpAfqcxbOjFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);